// AUTO-GENERATED by `xtask gen-ts`. Do not edit.
// Client for the "Physics" worker. Talks over a Transport (call -> Promise<Uint8Array>)
// with postcard as the wire codec (import the runtime below).

import type { Transport } from "./transport";
import { encode, decode } from "./postcard";

export class PhysicsClient {
  constructor(private readonly t: Transport) {}
  async step(state: number[], dt: number): Promise<number[]> {
    const resp = await this.t.call("Physics", 0, encode([state, dt]));
    return decode<number[]>(resp);
  }
  async apply_force(body_id: number, fx: number, fy: number, fz: number): Promise<boolean> {
    const resp = await this.t.call("Physics", 1, encode([body_id, fx, fy, fz]));
    return decode<boolean>(resp);
  }
}
