// AUTO-GENERATED by `xtask gen-ts-runtime`. Do not edit.
// Minimal postcard codec (serde-compatible). Replace with a full impl if needed.

export function encode(value: any): Uint8Array {
  // Simple JSON fallback — replace with postcard for binary compat.
  const json = JSON.stringify(value);
  const enc = new TextEncoder();
  return enc.encode(json);
}

export function decode<T>(bytes: Uint8Array): T {
  const dec = new TextDecoder();
  return JSON.parse(dec.decode(bytes));
}
