// AUTO-GENERATED by #[rpc]. Do not edit.
// Source trait: AssetLoader
import { RpcTransport, concat, decodeBytes, decodeU64, encodeString, encodeU32, encodeU64 } from './codec.ts';
import { AsyncWorker, asyncWorkerImports } from './async-worker.ts';
import { Rpc } from './rpc.ts';

export class AssetLoaderClient {
  private rpc: RpcTransport;
  private closed = false;

  /// Spawn the async worker. Instantiates the wasm module, wires the
  /// fetch imports, and returns a ready-to-use client. Call poll()
  /// each frame to drive the executor + resolve pending promises.
  static async spawn(workerWasmUrl = 'assetloader.wasm', baseUrl = ''): Promise<AssetLoaderClient> {
    const driver = new AsyncWorker(null, baseUrl);
    const memory = new WebAssembly.Memory({ shared: true, initial: 256, maximum: 1024 });
    const { instance } = await WebAssembly.instantiate(
      await (await fetch(workerWasmUrl)).arrayBuffer(),
      asyncWorkerImports(driver, memory),
    );
    driver.w = instance.exports;
    instance.exports.afterglow_wasm_init();
    return new AssetLoaderClient(driver);
  }

  /// Spawn the service in a real Web Worker using the shared-ring transport.
  static async spawnThreaded(opts: { mainWasmUrl?: string; workerJsUrl?: string; workerWasmUrl?: string; timeoutMs?: number } = {}): Promise<AssetLoaderClient> {
    const rpc = await Rpc.create({
      mainWasmUrl: opts.mainWasmUrl ?? 'afterglow_rpc.wasm',
      workerJsUrl: opts.workerJsUrl ?? 'worker.js',
      workerWasmUrl: opts.workerWasmUrl ?? 'assetloader.wasm',
      timeoutMs: opts.timeoutMs,
    });
    return new AssetLoaderClient(rpc);
  }

  /// Drive a locally instantiated async service. Threaded clients do not require polling.
  poll(): void { this.rpc.poll?.(); }

  constructor(rpc: RpcTransport) { this.rpc = rpc; }

  /// Idempotently stop an owned worker transport when supported.
  close(): void { if (this.closed) return; this.closed = true; this.rpc.terminate?.(); }

  async load(path: string): Promise<Uint8Array> {
    const args = encodeString(path);
    const resp = await this.rpc.call(0, args);
    return decodeBytes(resp, 0)[0];
  }

  async size(path: string): Promise<number> {
    const args = encodeString(path);
    const resp = await this.rpc.call(1, args);
    return decodeU64(resp, 0)[0];
  }

  async read(path: string, offset: number, len: number): Promise<Uint8Array> {
    const args = concat(encodeString(path), encodeU64(offset), encodeU32(len));
    const resp = await this.rpc.call(2, args);
    return decodeBytes(resp, 0)[0];
  }
}
