// AUTO-GENERATED by #[rpc]. Do not edit.
// Source trait: AsyncTypeMatrix
import { RpcTransport, concat, decodeBool, decodeBytes, decodeF32, decodeF32Vec, decodeI64, decodeString, decodeU32, decodeU64, encodeBool, encodeBytes, encodeF32, encodeF32Vec, encodeI64, encodeString, encodeU32, encodeU64 } from './codec.ts';
import { AsyncWorker, asyncWorkerImports } from './async-worker.ts';
import { Rpc } from './rpc.ts';

export class AsyncTypeMatrixClient {
  private rpc: RpcTransport;
  private closed = false;

  /// Spawn the async worker. Instantiates the wasm module, wires the
  /// fetch imports, and returns a ready-to-use client. Call poll()
  /// each frame to drive the executor + resolve pending promises.
  static async spawn(workerWasmUrl = 'asynctypematrix.wasm', baseUrl = ''): Promise<AsyncTypeMatrixClient> {
    const driver = new AsyncWorker(null, baseUrl);
    const memory = new WebAssembly.Memory({ shared: true, initial: 256, maximum: 1024 });
    const { instance } = await WebAssembly.instantiate(
      await (await fetch(workerWasmUrl)).arrayBuffer(),
      asyncWorkerImports(driver, memory),
    );
    driver.w = instance.exports;
    instance.exports.afterglow_wasm_init();
    return new AsyncTypeMatrixClient(driver);
  }

  /// Spawn the service in a real Web Worker using the shared-ring transport.
  static async spawnThreaded(opts: { mainWasmUrl?: string; workerJsUrl?: string; workerWasmUrl?: string; timeoutMs?: number } = {}): Promise<AsyncTypeMatrixClient> {
    const rpc = await Rpc.create({
      mainWasmUrl: opts.mainWasmUrl ?? 'afterglow_rpc.wasm',
      workerJsUrl: opts.workerJsUrl ?? 'worker.js',
      workerWasmUrl: opts.workerWasmUrl ?? 'asynctypematrix.wasm',
      timeoutMs: opts.timeoutMs,
    });
    return new AsyncTypeMatrixClient(rpc);
  }

  /// Drive a locally instantiated async service. Threaded clients do not require polling.
  poll(): void { this.rpc.poll?.(); }

  constructor(rpc: RpcTransport) { this.rpc = rpc; }

  /// Idempotently stop an owned worker transport when supported.
  close(): void { if (this.closed) return; this.closed = true; this.rpc.terminate?.(); }

  async echoF32(x: number): Promise<number> {
    const args = encodeF32(x);
    const resp = await this.rpc.call(0, args);
    return decodeF32(resp, 0)[0];
  }

  async echoU32(x: number): Promise<number> {
    const args = encodeU32(x);
    const resp = await this.rpc.call(1, args);
    return decodeU32(resp, 0)[0];
  }

  async echoU64(x: number): Promise<number> {
    const args = encodeU64(x);
    const resp = await this.rpc.call(2, args);
    return decodeU64(resp, 0)[0];
  }

  async echoI64(x: number): Promise<number> {
    const args = encodeI64(x);
    const resp = await this.rpc.call(3, args);
    return decodeI64(resp, 0)[0];
  }

  async echoBool(x: boolean): Promise<boolean> {
    const args = encodeBool(x);
    const resp = await this.rpc.call(4, args);
    return decodeBool(resp, 0)[0];
  }

  async echoString(s: string): Promise<string> {
    const args = encodeString(s);
    const resp = await this.rpc.call(5, args);
    return decodeString(resp, 0)[0];
  }

  async echoVecU8(v: Uint8Array): Promise<Uint8Array> {
    const args = encodeBytes(v);
    const resp = await this.rpc.call(6, args);
    return decodeBytes(resp, 0)[0];
  }

  async echoVecF32(v: Float32Array): Promise<Float32Array> {
    const args = encodeF32Vec(v);
    const resp = await this.rpc.call(7, args);
    return decodeF32Vec(resp, 0)[0];
  }

  async multi(a: number, b: string, c: boolean): Promise<number> {
    const args = concat(encodeU32(a), encodeString(b), encodeBool(c));
    const resp = await this.rpc.call(8, args);
    return decodeU64(resp, 0)[0];
  }

  async noArgs(): Promise<number> {
    const args = new Uint8Array();
    const resp = await this.rpc.call(9, args);
    return decodeU32(resp, 0)[0];
  }

  async void(x: number): Promise<void> {
    const args = encodeU32(x);
    await this.rpc.call(10, args);
  }
}
