// AUTO-GENERATED by #[rpc]. Do not edit.
// Source trait: EngineAudioService
import { RpcTransport, concat, decodeF64Vec, decodeI32, decodeU32, encodeBool, encodeBytes, encodeF32, encodeU32 } from './codec.ts';
import { Rpc } from './rpc.ts';

export class EngineAudioServiceClient {
  private rpc: RpcTransport;
  private closed = false;

  /// Spawn the sync worker. Instantiates the shared wasm + worker,
  /// and returns a ready-to-use client.
  static async spawn(opts: { mainWasmUrl?: string; workerJsUrl?: string; workerWasmUrl?: string; timeoutMs?: number } = {}): Promise<EngineAudioServiceClient> {
    const rpc = await Rpc.create({
      mainWasmUrl: opts.mainWasmUrl ?? 'afterglow_rpc.wasm',
      workerJsUrl: opts.workerJsUrl ?? 'worker.js',
      workerWasmUrl: opts.workerWasmUrl ?? 'engineaudioservice.wasm',
      timeoutMs: opts.timeoutMs,
    });
    return new EngineAudioServiceClient(rpc);
  }

  constructor(rpc: RpcTransport) { this.rpc = rpc; }

  /// Idempotently stop an owned worker transport when supported.
  close(): void { if (this.closed) return; this.closed = true; this.rpc.terminate?.(); }

  async configure(targetQuanta: number, triangles: number, reflectionRays: number, reflectionBounces: number, reflectionDurationMs: number, reflectionOrder: number): Promise<number> {
    const args = concat(encodeU32(targetQuanta), encodeU32(triangles), encodeU32(reflectionRays), encodeU32(reflectionBounces), encodeU32(reflectionDurationMs), encodeU32(reflectionOrder));
    const resp = await this.rpc.call(0, args);
    return decodeI32(resp, 0)[0];
  }

  async start(): Promise<number> {
    const args = new Uint8Array();
    const resp = await this.rpc.call(1, args);
    return decodeI32(resp, 0)[0];
  }

  async stop(): Promise<number> {
    const args = new Uint8Array();
    const resp = await this.rpc.call(2, args);
    return decodeI32(resp, 0)[0];
  }

  async updateMotion(phase: number): Promise<number> {
    const args = encodeF32(phase);
    const resp = await this.rpc.call(3, args);
    return decodeI32(resp, 0)[0];
  }

  async runSimulation(): Promise<number> {
    const args = new Uint8Array();
    const resp = await this.rpc.call(4, args);
    return decodeI32(resp, 0)[0];
  }

  async stats(): Promise<Float64Array> {
    const args = new Uint8Array();
    const resp = await this.rpc.call(5, args);
    return decodeF64Vec(resp, 0)[0];
  }

  async shutdown(): Promise<number> {
    const args = new Uint8Array();
    const resp = await this.rpc.call(6, args);
    return decodeI32(resp, 0)[0];
  }

  async spawn2d(sound: number): Promise<number> {
    const args = encodeU32(sound);
    const resp = await this.rpc.call(7, args);
    return decodeU32(resp, 0)[0];
  }

  async spawnAt(sound: number, x: number, y: number, z: number): Promise<number> {
    const args = concat(encodeU32(sound), encodeF32(x), encodeF32(y), encodeF32(z));
    const resp = await this.rpc.call(8, args);
    return decodeU32(resp, 0)[0];
  }

  async spawnAttached(sound: number, entity: number): Promise<number> {
    const args = concat(encodeU32(sound), encodeU32(entity));
    const resp = await this.rpc.call(9, args);
    return decodeU32(resp, 0)[0];
  }

  async spawnSpatialOnly(sound: number, x: number, y: number, z: number): Promise<number> {
    const args = concat(encodeU32(sound), encodeF32(x), encodeF32(y), encodeF32(z));
    const resp = await this.rpc.call(10, args);
    return decodeU32(resp, 0)[0];
  }

  async spawnListenerRelative(sound: number, x: number, y: number, z: number): Promise<number> {
    const args = concat(encodeU32(sound), encodeF32(x), encodeF32(y), encodeF32(z));
    const resp = await this.rpc.call(11, args);
    return decodeU32(resp, 0)[0];
  }

  async crossfade(from: number, to: number, seconds: number): Promise<number> {
    const args = concat(encodeU32(from), encodeU32(to), encodeF32(seconds));
    const resp = await this.rpc.call(12, args);
    return decodeI32(resp, 0)[0];
  }

  async crossfadeTo(from: number, sound: number, seconds: number): Promise<number> {
    const args = concat(encodeU32(from), encodeU32(sound), encodeF32(seconds));
    const resp = await this.rpc.call(13, args);
    return decodeU32(resp, 0)[0];
  }

  async setVoiceVolume(handle: number, volume: number, seconds: number): Promise<number> {
    const args = concat(encodeU32(handle), encodeF32(volume), encodeF32(seconds));
    const resp = await this.rpc.call(14, args);
    return decodeI32(resp, 0)[0];
  }

  async pauseVoice(handle: number, seconds: number): Promise<number> {
    const args = concat(encodeU32(handle), encodeF32(seconds));
    const resp = await this.rpc.call(15, args);
    return decodeI32(resp, 0)[0];
  }

  async resumeVoice(handle: number, seconds: number): Promise<number> {
    const args = concat(encodeU32(handle), encodeF32(seconds));
    const resp = await this.rpc.call(16, args);
    return decodeI32(resp, 0)[0];
  }

  async stopVoice(handle: number, seconds: number): Promise<number> {
    const args = concat(encodeU32(handle), encodeF32(seconds));
    const resp = await this.rpc.call(17, args);
    return decodeI32(resp, 0)[0];
  }

  async loadWav(data: Uint8Array, looped: boolean): Promise<number> {
    const args = concat(encodeBytes(data), encodeBool(looped));
    const resp = await this.rpc.call(18, args);
    return decodeU32(resp, 0)[0];
  }

  async unloadSound(handle: number): Promise<number> {
    const args = encodeU32(handle);
    const resp = await this.rpc.call(19, args);
    return decodeI32(resp, 0)[0];
  }

  async beginWavUpload(totalBytes: number, looped: boolean): Promise<number> {
    const args = concat(encodeU32(totalBytes), encodeBool(looped));
    const resp = await this.rpc.call(20, args);
    return decodeI32(resp, 0)[0];
  }

  async appendWavUpload(data: Uint8Array): Promise<number> {
    const args = encodeBytes(data);
    const resp = await this.rpc.call(21, args);
    return decodeI32(resp, 0)[0];
  }

  async finishWavUpload(): Promise<number> {
    const args = new Uint8Array();
    const resp = await this.rpc.call(22, args);
    return decodeU32(resp, 0)[0];
  }

  async beginAcousticSceneUpload(totalBytes: number): Promise<number> {
    const args = encodeU32(totalBytes);
    const resp = await this.rpc.call(23, args);
    return decodeI32(resp, 0)[0];
  }

  async appendAcousticSceneUpload(data: Uint8Array): Promise<number> {
    const args = encodeBytes(data);
    const resp = await this.rpc.call(24, args);
    return decodeI32(resp, 0)[0];
  }

  async finishAcousticSceneUpload(): Promise<number> {
    const args = new Uint8Array();
    const resp = await this.rpc.call(25, args);
    return decodeI32(resp, 0)[0];
  }
}
