// AUTO-GENERATED by #[rpc]. Do not edit.
// Source trait: Meshopt
import { RpcTransport, concat, decodeBytes, decodeF32Vec, decodeU16, decodeU32Vec, encodeBytes, encodeF32, encodeF32Vec, encodeU32, encodeU32Vec } from './codec.ts';
import { AsyncWorker, asyncWorkerImports } from './async-worker.ts';
import { Rpc } from './rpc.ts';

export class MeshoptClient {
  private rpc: RpcTransport;
  private closed = false;

  /// Spawn the async worker. Instantiates the wasm module, wires the
  /// fetch imports, and returns a ready-to-use client. Call poll()
  /// each frame to drive the executor + resolve pending promises.
  static async spawn(workerWasmUrl = 'meshopt.wasm', baseUrl = ''): Promise<MeshoptClient> {
    const driver = new AsyncWorker(null, baseUrl);
    const memory = new WebAssembly.Memory({ shared: true, initial: 256, maximum: 1024 });
    const { instance } = await WebAssembly.instantiate(
      await (await fetch(workerWasmUrl)).arrayBuffer(),
      asyncWorkerImports(driver, memory),
    );
    driver.w = instance.exports;
    instance.exports.afterglow_wasm_init();
    return new MeshoptClient(driver);
  }

  /// Spawn the service in a real Web Worker using the shared-ring transport.
  static async spawnThreaded(opts: { mainWasmUrl?: string; workerJsUrl?: string; workerWasmUrl?: string; timeoutMs?: number } = {}): Promise<MeshoptClient> {
    const rpc = await Rpc.create({
      mainWasmUrl: opts.mainWasmUrl ?? 'afterglow_rpc.wasm',
      workerJsUrl: opts.workerJsUrl ?? 'worker.js',
      workerWasmUrl: opts.workerWasmUrl ?? 'meshopt.wasm',
      timeoutMs: opts.timeoutMs,
    });
    return new MeshoptClient(rpc);
  }

  /// Drive a locally instantiated async service. Threaded clients do not require polling.
  poll(): void { this.rpc.poll?.(); }

  constructor(rpc: RpcTransport) { this.rpc = rpc; }

  /// Idempotently stop an owned worker transport when supported.
  close(): void { if (this.closed) return; this.closed = true; this.rpc.terminate?.(); }

  async simplify(indices: Uint32Array, positions: Float32Array, positionStride: number, targetIndexCount: number, targetError: number): Promise<Uint32Array> {
    const args = concat(encodeU32Vec(indices), encodeF32Vec(positions), encodeU32(positionStride), encodeU32(targetIndexCount), encodeF32(targetError));
    const resp = await this.rpc.call(0, args);
    return decodeU32Vec(resp, 0)[0];
  }

  async simplifySloppy(indices: Uint32Array, positions: Float32Array, positionStride: number, targetIndexCount: number, targetError: number): Promise<Uint32Array> {
    const args = concat(encodeU32Vec(indices), encodeF32Vec(positions), encodeU32(positionStride), encodeU32(targetIndexCount), encodeF32(targetError));
    const resp = await this.rpc.call(1, args);
    return decodeU32Vec(resp, 0)[0];
  }

  async simplifyWithUvs(indices: Uint32Array, positions: Float32Array, positionStride: number, uvs: Float32Array, uvStride: number, uvWeight: number, targetIndexCount: number, targetError: number): Promise<Uint32Array> {
    const args = concat(encodeU32Vec(indices), encodeF32Vec(positions), encodeU32(positionStride), encodeF32Vec(uvs), encodeU32(uvStride), encodeF32(uvWeight), encodeU32(targetIndexCount), encodeF32(targetError));
    const resp = await this.rpc.call(2, args);
    return decodeU32Vec(resp, 0)[0];
  }

  async simplifyWithAttributes(indices: Uint32Array, positions: Float32Array, positionStride: number, attributes: Float32Array, attributeStride: number, attributeWeights: Float32Array, vertexLock: Uint8Array, targetIndexCount: number, targetError: number): Promise<Uint32Array> {
    const args = concat(encodeU32Vec(indices), encodeF32Vec(positions), encodeU32(positionStride), encodeF32Vec(attributes), encodeU32(attributeStride), encodeF32Vec(attributeWeights), encodeBytes(vertexLock), encodeU32(targetIndexCount), encodeF32(targetError));
    const resp = await this.rpc.call(3, args);
    return decodeU32Vec(resp, 0)[0];
  }

  async optimizeVertexCache(indices: Uint32Array, vertexCount: number): Promise<Uint32Array> {
    const args = concat(encodeU32Vec(indices), encodeU32(vertexCount));
    const resp = await this.rpc.call(4, args);
    return decodeU32Vec(resp, 0)[0];
  }

  async optimizeOverdraw(indices: Uint32Array, positions: Float32Array, positionStride: number, threshold: number): Promise<Uint32Array> {
    const args = concat(encodeU32Vec(indices), encodeF32Vec(positions), encodeU32(positionStride), encodeF32(threshold));
    const resp = await this.rpc.call(5, args);
    return decodeU32Vec(resp, 0)[0];
  }

  async encodeIndexBuffer(indices: Uint32Array, vertexCount: number): Promise<Uint8Array> {
    const args = concat(encodeU32Vec(indices), encodeU32(vertexCount));
    const resp = await this.rpc.call(6, args);
    return decodeBytes(resp, 0)[0];
  }

  async decodeIndexBuffer(buffer: Uint8Array, indexCount: number): Promise<Uint32Array> {
    const args = concat(encodeBytes(buffer), encodeU32(indexCount));
    const resp = await this.rpc.call(7, args);
    return decodeU32Vec(resp, 0)[0];
  }

  async encodeVertexBuffer(vertices: Uint8Array, vertexSize: number): Promise<Uint8Array> {
    const args = concat(encodeBytes(vertices), encodeU32(vertexSize));
    const resp = await this.rpc.call(8, args);
    return decodeBytes(resp, 0)[0];
  }

  async decodeVertexBuffer(buffer: Uint8Array, vertexCount: number, vertexSize: number): Promise<Uint8Array> {
    const args = concat(encodeBytes(buffer), encodeU32(vertexCount), encodeU32(vertexSize));
    const resp = await this.rpc.call(9, args);
    return decodeBytes(resp, 0)[0];
  }

  async generateVertexRemap(indices: Uint32Array, vertices: Uint8Array, vertexSize: number): Promise<Uint32Array> {
    const args = concat(encodeU32Vec(indices), encodeBytes(vertices), encodeU32(vertexSize));
    const resp = await this.rpc.call(10, args);
    return decodeU32Vec(resp, 0)[0];
  }

  async stripify(indices: Uint32Array, vertexCount: number, restartIndex: number): Promise<Uint32Array> {
    const args = concat(encodeU32Vec(indices), encodeU32(vertexCount), encodeU32(restartIndex));
    const resp = await this.rpc.call(11, args);
    return decodeU32Vec(resp, 0)[0];
  }

  async buildMeshlets(indices: Uint32Array, positions: Float32Array, positionStride: number, maxVertices: number, maxTriangles: number, coneWeight: number): Promise<Uint8Array> {
    const args = concat(encodeU32Vec(indices), encodeF32Vec(positions), encodeU32(positionStride), encodeU32(maxVertices), encodeU32(maxTriangles), encodeF32(coneWeight));
    const resp = await this.rpc.call(12, args);
    return decodeBytes(resp, 0)[0];
  }

  async analyzeVertexCache(indices: Uint32Array, vertexCount: number): Promise<Float32Array> {
    const args = concat(encodeU32Vec(indices), encodeU32(vertexCount));
    const resp = await this.rpc.call(13, args);
    return decodeF32Vec(resp, 0)[0];
  }

  async quantizeHalf(value: number): Promise<number> {
    const args = encodeF32(value);
    const resp = await this.rpc.call(14, args);
    return decodeU16(resp, 0)[0];
  }
}
