// AUTO-GENERATED by #[rpc]. Do not edit.
// Source trait: Paint
import { RpcTransport, concat, decodeBytes, decodeString, encodeBytes, encodeI32, encodeString, encodeU32 } from './codec.ts';
import { AsyncWorker, asyncWorkerImports } from './async-worker.ts';
import { Rpc } from './rpc.ts';

export class PaintClient {
  private rpc: RpcTransport;
  private closed = false;

  /// Spawn the async worker. Instantiates the wasm module, wires the
  /// fetch imports, and returns a ready-to-use client. Call poll()
  /// each frame to drive the executor + resolve pending promises.
  static async spawn(workerWasmUrl = 'paint.wasm', baseUrl = ''): Promise<PaintClient> {
    const driver = new AsyncWorker(null, baseUrl);
    const memory = new WebAssembly.Memory({ shared: true, initial: 256, maximum: 1024 });
    const { instance } = await WebAssembly.instantiate(
      await (await fetch(workerWasmUrl)).arrayBuffer(),
      asyncWorkerImports(driver, memory),
    );
    driver.w = instance.exports;
    (instance.exports.afterglow_wasm_init as () => void)();
    return new PaintClient(driver);
  }

  /// Spawn the service in a real Web Worker using the shared-ring transport.
  static async spawnThreaded(opts: { mainWasmUrl?: string; workerJsUrl?: string; workerWasmUrl?: string; timeoutMs?: number } = {}): Promise<PaintClient> {
    const rpc = await Rpc.create({
      mainWasmUrl: opts.mainWasmUrl ?? 'afterglow_rpc.wasm',
      workerJsUrl: opts.workerJsUrl ?? 'worker.js',
      workerWasmUrl: opts.workerWasmUrl ?? 'paint.wasm',
      timeoutMs: opts.timeoutMs,
    });
    return new PaintClient(rpc);
  }

  /// Drive a locally instantiated async service. Threaded clients do not require polling.
  poll(): void { this.rpc.poll?.(); }

  constructor(rpc: RpcTransport) { this.rpc = rpc; }

  /// Idempotently stop an owned worker transport when supported.
  close(): void { if (this.closed) return; this.closed = true; this.rpc.terminate?.(); }

  async command(commandJson: string): Promise<string> {
    const args = encodeString(commandJson);
    const resp = await this.rpc.call(0, args);
    return decodeString(resp, 0)[0];
  }

  async tile(layer: number, tx: number, ty: number, scale: number): Promise<Uint8Array> {
    const args = concat(encodeI32(layer), encodeI32(tx), encodeI32(ty), encodeU32(scale));
    const resp = await this.rpc.call(1, args);
    return decodeBytes(resp, 0)[0];
  }

  async writeTile(layer: number, tx: number, ty: number, data: Uint8Array): Promise<string> {
    const args = concat(encodeU32(layer), encodeI32(tx), encodeI32(ty), encodeBytes(data));
    const resp = await this.rpc.call(2, args);
    return decodeString(resp, 0)[0];
  }
}
