use serde::{Deserialize, Serialize};

/// Number of characters in each hyphenated group of a session code.
pub const SESSION_CODE_GROUP_LEN: usize = 3;

/// Number of groups in a session code.
pub const SESSION_CODE_GROUPS: usize = 2;

/// Total characters in a session code, excluding the hyphen separator.
pub const SESSION_CODE_CHAR_LEN: usize = SESSION_CODE_GROUP_LEN * SESSION_CODE_GROUPS;

/// Character set used for session codes.
///
/// Uppercase A–Z with visually/confusingly similar letters removed (I, L, O)
/// so codes are easier to read aloud and harder to mistype.
pub const SESSION_CODE_ALPHABET: &[u8] = b"ABCDEFGHJKMNPQRSTUVWXYZ";

/// Player-facing short code used to identify and join a session.
///
/// Internally sessions still have a durable [`super::SessionId`], but players
/// see and share codes like `XFQ-KRB`. Codes are generated by the non-Steam
/// session provider on creation and are unique among active sessions.
#[derive(
    Clone,
    Debug,
    Default,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
    Serialize,
    Deserialize,
    bevy::prelude::Reflect,
)]
pub struct SessionCode(pub String);

impl SessionCode {
    /// Create a code from any string. Useful for tests or manual entry.
    pub fn new(code: impl Into<String>) -> Self {
        Self(code.into())
    }

    /// Borrow the underlying string.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Generate a short, memorable code from a counter value.
    ///
    /// The counter is mixed with a simple 64-bit permutation so sequential
    /// session IDs do not produce sequential-looking codes. The same counter
    /// always produces the same code, which makes tests deterministic.
    pub fn generate(counter: u64) -> Self {
        let alphabet_len = SESSION_CODE_ALPHABET.len() as u64;
        let mut n = Self::mix64(counter);
        let mut chars = [b'A'; SESSION_CODE_CHAR_LEN];

        for ch in chars.iter_mut().take(SESSION_CODE_CHAR_LEN) {
            *ch = SESSION_CODE_ALPHABET[(n % alphabet_len) as usize];
            n /= alphabet_len;
        }

        let group1 = std::str::from_utf8(&chars[..SESSION_CODE_GROUP_LEN]).unwrap();
        let group2 = std::str::from_utf8(&chars[SESSION_CODE_GROUP_LEN..]).unwrap();
        Self(format!("{}-{}", group1, group2))
    }

    /// SplitMix64 — fast, deterministic 64-bit mixer with good avalanche.
    fn mix64(x: u64) -> u64 {
        let mut z = x.wrapping_add(0x9e3779b97f4a7c15);
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d049bb133111eb);
        z ^ (z >> 31)
    }
}

impl From<&str> for SessionCode {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

impl From<String> for SessionCode {
    fn from(value: String) -> Self {
        Self(value)
    }
}
