[target.wasm32-unknown-unknown]
rustflags = [
  '-C', 'target-feature=+atomics,+bulk-memory,+mutable-globals',
  '-C', 'link-arg=--import-memory',
  '-C', 'link-arg=--max-memory=67108864',
  '-C', 'link-arg=--shared-memory',
]
