// AssetStore — bridges the AssetLoaderClient (raw bytes over RPC) with Three.js.
//
// The asset worker (`afterglow-assets-worker`) loads raw `Uint8Array` bytes from
// disk (native) or via fetch (web). The AssetStore parses those bytes into
// Three.js objects (textures, geometries, GLTF models) and caches them by path.
//
// The store is an ECS Resource — one instance per world, accessed via:
//   const store = AssetStoreRes.get(world);
//
// Loading is async (poll model): `loadTexture(path)` returns a Promise that
// resolves when the worker delivers the bytes AND the parser finishes. The
// caller must call `store.poll()` each frame to drive the async worker and
// resolve pending promises. Already-cached assets are returned synchronously
// via `get(path)`.
//
// Custom asset types are supported via pluggable parsers:
//   const myGeom = await store.load('mesh.bin', parseCustomGeometry);

import * as THREE from 'three';

import { Resource, defineResource } from './resource.js';

/** Maximum bytes a single `load()` call can return (the response ring size). */
const MAX_SINGLE_LOAD = 1 << 20; // 1 MiB
/** Chunk size for streaming large assets. */
const CHUNK_SIZE = 512 * 1024; // 512 KiB

// --- asset loader interface (what AssetLoaderClient implements) -----------

/**
 * The async asset loader interface. `AssetLoaderClient` (generated by `#[rpc]`)
 * implements this. The poll model means `load()` returns a Promise that only
 * resolves after `poll()` delivers the completion.
 */
export interface AssetLoader {
  /** Load a full asset as raw bytes. */
  load(path: string): Promise<Uint8Array>;
  /** Get the size of an asset in bytes (for planning chunked reads). */
  size(path: string): Promise<number>;
  /** Read a range of bytes (for streaming large assets). */
  read(path: string, offset: number, len: number): Promise<Uint8Array>;
  /** Drive the async executor — call each frame to resolve pending loads. */
  poll(): void;
}

/** A parser that turns raw bytes into a typed asset. */
export type AssetParser<T> = (bytes: Uint8Array) => Promise<T> | T;

/** A loaded asset entry in the cache. */
interface CacheEntry<T> {
  readonly asset: T;
  /** Reference count for future eviction (not yet used). */
  refCount: number;
}

// --- parsers for common Three.js asset types ------------------------------

/**
 * Parse image bytes (PNG, JPEG, etc.) into a `THREE.Texture`.
 * Uses `createImageBitmap` (GPU-accelerated, no DOM needed).
 */
export async function parseTexture(bytes: Uint8Array): Promise<THREE.Texture> {
  const blob = new Blob([bytes]);
  const bitmap = await createImageBitmap(blob);
  const texture = new THREE.Texture(bitmap);
  texture.needsUpdate = true;
  texture.colorSpace = THREE.SRGBColorSpace;
  return texture;
}

/**
 * Parse an image into a `THREE.DataTexture` (for when you need raw pixel access).
 * Falls back to the bitmap texture if the image can't be decoded synchronously.
 */
export async function parseDataTexture(bytes: Uint8Array): Promise<THREE.Texture> {
  // Same as parseTexture — createImageBitmap is the most portable path.
  // For true DataTexture (raw RGBA), use a custom parser with a known format.
  return parseTexture(bytes);
}

/**
 * Parse GLTF/GLB bytes into a `THREE.Group` containing the model.
 * Uses `GLTFLoader.parse()` if available; throws otherwise.
 *
 * Note: GLTFLoader must be imported and available on `THREE.GLTFLoader` or
 * passed as a dependency. The `three.webgpu.js` bundle includes it.
 */
export async function parseGLTF(
  bytes: Uint8Array,
  loader?: { parse(data: ArrayBuffer, path: string, onLoad: (result: { scene: THREE.Group }) => void, onError: (e: unknown) => void): void },
): Promise<THREE.Group> {
  // Copy into a standalone ArrayBuffer (GLTFLoader expects one).
  const buffer = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(buffer).set(bytes);

  if (loader) {
    return new Promise((resolve, reject) => {
      loader.parse(
        buffer,
        '',
        (result) => resolve(result.scene),
        reject,
      );
    });
  }

  // Try THREE.GLTFLoader (available in the full three.webgpu.js bundle).
  const GLTFLoader = (THREE as unknown as Record<string, unknown>).GLTFLoader as
    | (new () => { parse(data: ArrayBuffer, path: string, onLoad: (r: { scene: THREE.Group }) => void, onError: (e: unknown) => void): void })
    | undefined;

  if (!GLTFLoader) {
    throw new Error('GLTFLoader not available — pass a loader instance or include three examples');
  }

  const gltfLoader = new GLTFLoader();
  return new Promise((resolve, reject) => {
    gltfLoader.parse(buffer, '', (result) => resolve(result.scene), reject);
  });
}

/**
 * Parse raw bytes as a JSON object (for material definitions, scene
 * descriptions, etc.).
 */
export function parseJSON<T = unknown>(bytes: Uint8Array): T {
  return JSON.parse(new TextDecoder().decode(bytes)) as T;
}

// --- AssetStore ----------------------------------------------------------

/**
 * Bridges the async asset worker with Three.js. Loads raw bytes via the
 * `AssetLoader` interface, parses them into Three.js objects, and caches
 * by path. Cached assets are returned synchronously.
 *
 * Register as an ECS resource:
 * ```ts
 * const store = new AssetStore(loader);
 * AssetStoreRes.set(world, store);
 * ```
 *
 * Use in systems:
 * ```ts
 * const store = AssetStoreRes.get(world);
 * store.poll();  // drive async loads
 * const tex = store.get<THREE.Texture>('textures/sky.png');  // sync, if cached
 * if (!tex) store.loadTexture('textures/sky.png').then(t => { ... });
 * ```
 */
export class AssetStore {
  /** Parsed assets keyed by path. */
  private readonly cache = new Map<string, CacheEntry<unknown>>();
  /** In-flight load promises keyed by path (prevents duplicate loads). */
  private readonly pending = new Map<string, Promise<unknown>>();

  constructor(private readonly loader: AssetLoader) {}

  /** The underlying asset loader (for direct byte access if needed). */
  get assetLoader(): AssetLoader {
    return this.loader;
  }

  /** Drive the async worker — call each frame to resolve pending loads. */
  poll(): void {
    this.loader.poll();
  }

  /**
   * Load an asset with a custom parser. Returns a cached asset immediately
   * if already loaded. Prevents duplicate loads of the same path.
   *
   * If the asset exceeds the 1 MiB response ring, the store automatically
   * falls back to chunked `size` + `read` calls internally.
   */
  async load<T>(path: string, parser: AssetParser<T>, onProgress?: ProgressFn): Promise<T> {
    // Return cached immediately.
    const cached = this.cache.get(path);
    if (cached) return cached.asset as T;

    // Return in-flight promise if loading.
    const inflight = this.pending.get(path);
    if (inflight) return inflight as Promise<T>;

    // Start a new load.
    const promise = (async () => {
      // If the asset is larger than the 1 MiB response ring, chunk it.
      let bytes: Uint8Array;
      const total = await this.loader.size(path);
      if (total > MAX_SINGLE_LOAD) {
        bytes = await this.loadChunked(path, total, onProgress);
      } else {
        bytes = await this.loader.load(path);
      }
      const asset = await parser(bytes);
      this.cache.set(path, { asset, refCount: 0 });
      return asset;
    })();

    this.pending.set(path, promise);
    try {
      return await promise as T;
    } finally {
      this.pending.delete(path);
    }
  }

  /**
   * Get a cached asset synchronously, or `undefined` if not yet loaded.
   * Use this in hot paths (render loop) to avoid awaiting.
   */
  get<T>(path: string): T | undefined {
    return this.cache.get(path)?.asset as T | undefined;
  }

  /** Is this asset cached and ready? */
  has(path: string): boolean {
    return this.cache.has(path);
  }

  /** Is this asset currently loading? */
  isLoading(path: string): boolean {
    return this.pending.has(path);
  }

  /** Load an image as a `THREE.Texture` (PNG, JPEG, etc.). */
  loadTexture(path: string, onProgress?: ProgressFn): Promise<THREE.Texture> {
    return this.load(path, parseTexture, onProgress);
  }

  /** Load a GLTF/GLB model as a `THREE.Group`. */
  loadGLTF(path: string, loader?: Parameters<typeof parseGLTF>[1], onProgress?: ProgressFn): Promise<THREE.Group> {
    return this.load(path, (bytes) => parseGLTF(bytes, loader), onProgress);
  }

  /** Load a JSON file (material defs, scene descriptions, etc.). */
  loadJSON<T = unknown>(path: string, onProgress?: ProgressFn): Promise<T> {
    return this.load(path, parseJSON<T>, onProgress);
  }

  /** Internal: chunked load for assets larger than the 1 MiB response ring. */
  private async loadChunked(path: string, total: number, onProgress?: ProgressFn): Promise<Uint8Array> {
    const chunks: Uint8Array[] = [];
    let offset = 0;
    while (offset < total) {
      const len = Math.min(CHUNK_SIZE, total - offset);
      const chunk = await this.loader.read(path, offset, len);
      chunks.push(chunk);
      offset += chunk.byteLength;
      onProgress?.(offset, total);
    }
    const bytes = new Uint8Array(total);
    let pos = 0;
    for (const chunk of chunks) {
      bytes.set(chunk, pos);
      pos += chunk.byteLength;
    }
    return bytes;
  }

  /** Remove an asset from the cache (does not dispose GPU resources). */
  evict(path: string): void {
    this.cache.delete(path);
  }

  /** Number of cached assets. */
  get size(): number {
    return this.cache.size;
  }

  /** All cached asset paths. */
  get cachedPaths(): string[] {
    return [...this.cache.keys()];
  }

  /** Dispose all cached assets and clear the cache. */
  dispose(): void {
    for (const entry of this.cache.values()) {
      const asset = entry.asset as { dispose?: () => void };
      asset?.dispose?.();
    }
    this.cache.clear();
    this.pending.clear();
  }
}

// --- ECS Resource registration -------------------------------------------

/**
 * The AssetStore ECS resource. Lazily created — the factory throws if no
 * loader has been set via `AssetStoreRes.set(world, store)`. In practice,
 * you spawn the AssetLoaderClient async, then set the store:
 *
 * ```ts
 * const client = await AssetLoaderClient.spawn();
 * AssetStoreRes.set(world, new AssetStore(client));
 * ```
 *
 * Systems that only read can use `AssetStoreRes.get(world)` safely after
 * initialization.
 */
export const AssetStoreRes = defineResource<AssetStore>('assetStore', () => {
  throw new Error(
    'AssetStore resource not initialized. Call `AssetStoreRes.set(world, new AssetStore(client))` after spawning the AssetLoaderClient.',
  );
});
