// AUTO-GENERATED by #[rpc]. Do not edit.
// Source trait: Physics
import { RpcTransport, concat, decodeBool, decodeF32Vec, encodeF32, encodeF32Vec, encodeU32 } from './codec.ts';
import { Rpc } from './rpc.ts';

export class PhysicsClient {
  private rpc: RpcTransport;
  private closed = false;

  /// Spawn the sync worker. Instantiates the shared wasm + worker,
  /// and returns a ready-to-use client.
  static async spawn(opts: { mainWasmUrl?: string; workerJsUrl?: string; workerWasmUrl?: string; timeoutMs?: number } = {}): Promise<PhysicsClient> {
    const rpc = await Rpc.create({
      mainWasmUrl: opts.mainWasmUrl ?? 'afterglow_web.wasm',
      workerJsUrl: opts.workerJsUrl ?? 'worker.js',
      workerWasmUrl: opts.workerWasmUrl ?? 'physics.wasm',
      timeoutMs: opts.timeoutMs,
    });
    return new PhysicsClient(rpc);
  }

  constructor(rpc: RpcTransport) { this.rpc = rpc; }

  /// Idempotently stop an owned worker transport when supported.
  close(): void { if (this.closed) return; this.closed = true; this.rpc.terminate?.(); }

  async step(state: Float32Array, dt: number): Promise<Float32Array> {
    const args = concat(encodeF32Vec(state), encodeF32(dt));
    const resp = await this.rpc.call(0, args);
    return decodeF32Vec(resp, 0)[0];
  }

  async applyForce(bodyId: number, fx: number, fy: number, fz: number): Promise<boolean> {
    const args = concat(encodeU32(bodyId), encodeF32(fx), encodeF32(fy), encodeF32(fz));
    const resp = await this.rpc.call(1, args);
    return decodeBool(resp, 0)[0];
  }
}
