// AUTO-GENERATED by #[rpc]. Do not edit.
// Source trait: Texture
import { RpcTransport, concat, decodeBytes, encodeBytes, encodeU32 } from './codec.ts';
import { AsyncWorker, asyncWorkerImports } from './async-worker.ts';
import { Rpc } from './rpc.ts';

export class TextureClient {
  private rpc: RpcTransport;
  private closed = false;

  /// Spawn the async worker. Instantiates the wasm module, wires the
  /// fetch imports, and returns a ready-to-use client. Call poll()
  /// each frame to drive the executor + resolve pending promises.
  static async spawn(workerWasmUrl = 'texture.wasm', baseUrl = ''): Promise<TextureClient> {
    const driver = new AsyncWorker(null, baseUrl);
    const memory = new WebAssembly.Memory({ shared: true, initial: 256, maximum: 1024 });
    const { instance } = await WebAssembly.instantiate(
      await (await fetch(workerWasmUrl)).arrayBuffer(),
      asyncWorkerImports(driver, memory),
    );
    driver.w = instance.exports;
    instance.exports.afterglow_wasm_init();
    return new TextureClient(driver);
  }

  /// Spawn the service in a real Web Worker using the shared-ring transport.
  static async spawnThreaded(opts: { mainWasmUrl?: string; workerJsUrl?: string; workerWasmUrl?: string; timeoutMs?: number } = {}): Promise<TextureClient> {
    const rpc = await Rpc.create({
      mainWasmUrl: opts.mainWasmUrl ?? 'afterglow_web.wasm',
      workerJsUrl: opts.workerJsUrl ?? 'worker.js',
      workerWasmUrl: opts.workerWasmUrl ?? 'texture.wasm',
      timeoutMs: opts.timeoutMs,
    });
    return new TextureClient(rpc);
  }

  /// Drive a locally instantiated async service. Threaded clients do not require polling.
  poll(): void { this.rpc.poll?.(); }

  constructor(rpc: RpcTransport) { this.rpc = rpc; }

  /// Idempotently stop an owned worker transport when supported.
  close(): void { if (this.closed) return; this.closed = true; this.rpc.terminate?.(); }

  async transcode(data: Uint8Array, targetFormat: number): Promise<Uint8Array> {
    const args = concat(encodeBytes(data), encodeU32(targetFormat));
    const resp = await this.rpc.call(0, args);
    return decodeBytes(resp, 0)[0];
  }

  async generateMips(data: Uint8Array, width: number, height: number): Promise<Uint8Array> {
    const args = concat(encodeBytes(data), encodeU32(width), encodeU32(height));
    const resp = await this.rpc.call(1, args);
    return decodeBytes(resp, 0)[0];
  }

  async downscale(data: Uint8Array, width: number, height: number, targetWidth: number, targetHeight: number): Promise<Uint8Array> {
    const args = concat(encodeBytes(data), encodeU32(width), encodeU32(height), encodeU32(targetWidth), encodeU32(targetHeight));
    const resp = await this.rpc.call(2, args);
    return decodeBytes(resp, 0)[0];
  }
}
