import * as THREE from 'three/webgpu';
import {
  BigAssetSession, PersistentBlobCache, createAssetRangeSource,
  getVirtualTextureDimensions, loadHeightTextureR16, persistentCacheNamespace,
} from '../../engine/assets/index.ts';
import { EngineRuntime, RegistrationStatus, RendererHost, type RenderFrame } from '../../engine/index.ts';
import { BoundedKeyboardInput, DemoInputAction, RelativePointerInput } from '../../engine/input/index.ts';
import {
  FeedbackRegistrationStatus, FORMAT_RGBA, VirtualPomSceneBinding,
  VirtualTextureFeedbackCoordinator, VirtualTextureTuning, validatePomShaderWarmup,
} from '../../engine/virtual-texturing/index.ts';
import {
  BootstrapGuard, BrowserErrorCapture, FrameStepHarness, PageShutdown, TextHud,
  publishDevHarness,
} from '../../engine/diagnostics/index.ts';

const VT_QUALITY_BIAS=0, FEEDBACK_INTERVAL=8;
const POM_MIN_LAYERS=8,POM_MAX_LAYERS=32,POM_HEIGHT_SCALE=.05,POM_MAX_OFFSET_RATIO=2,POM_MAX_DISTANCE=0,POM_SHADOW_STEPS=8,POM_SHADOW_BIAS=.01,POM_SHADOW_STRENGTH=.82;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x101318);scene.fog=new THREE.Fog(0x101318,7,28);
const camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.05,60);camera.rotation.order='YXZ';
const runtime=EngineRuntime.forScene({scene,entityCapacity:1,memory:{frameScratchBytes:16384,renderScratchBytes:16384,structuralCommands:8,workerCompletions:8,assetRequests:8,vtRequests:512},diagnosticCapacity:128,maxWorkerInputs:1,maxRenderPasses:2});
let coordinator:VirtualTextureFeedbackCoordinator|null=null;
function resizeCamera(width:number,height:number):void{camera.aspect=width/height;camera.updateProjectionMatrix();const ratio=Math.min(2,Math.max(.1,devicePixelRatio));coordinator?.resize(width*ratio,height*ratio)}
const host=await RendererHost.create({scene,camera,diagnostics:runtime.diagnostics,parameters:{antialias:false,trackTimestamp:false},onResize:resizeCamera}).catch((error:unknown)=>{runtime.dispose();throw error});
const bootstrap=new BootstrapGuard(20);bootstrap.defer(()=>host.dispose());bootstrap.defer(()=>runtime.dispose());
try{
const source=createAssetRangeSource(),identity=await source.identity('dungeon.big');
const device=host.device,format=device.features.has('texture-compression-bc')?0:device.features.has('texture-compression-astc')?1:FORMAT_RGBA;
const adapterInfo=host.adapterInfo;let cache:PersistentBlobCache|undefined;
if(identity.etag||identity.lastModified){try{cache=await PersistentBlobCache.open({namespace:await persistentCacheNamespace(['afterglow-cache-v1','dungeon.big',String(identity.size),identity.etag??'',identity.lastModified??'',String(format),'basisu-transcoder-v1','slot-136-border-4',adapterInfo.vendor??'',adapterInfo.architecture??'',adapterInfo.device??'',adapterInfo.description??'']),maxBytes:1024*1024*1024,maxEntries:65536,writeQueueCapacity:64})}catch(error){console.warn('[cache] persistent blob cache unavailable:',error)}}
const workerCount=Math.max(2,Math.min(4,Math.floor((navigator.hardwareConcurrency||4)/2)));
const session=await BigAssetSession.open({containerPath:'dungeon.big',format,workerCount,transcodeQueueCapacity:64,maxHeaderBytes:2*1024*1024,source,...(cache?{cache}:{})});bootstrap.defer(()=>session.close());
const store=session.createVirtualTextureStore(device,new VirtualTextureTuning());bootstrap.defer(()=>store.dispose());
coordinator=new VirtualTextureFeedbackCoordinator(host.renderer,store,{renderables:1,passes:1,cadence:FEEDBACK_INTERVAL,scale:.125});
const activeCoordinator=coordinator;
activeCoordinator.resize(host.renderer.domElement.width,host.renderer.domElement.height);
const pomBinding=new VirtualPomSceneBinding({camera,store,feedbackPixelScale:coordinator.pixelScale,capacity:12,material:{minLayers:POM_MIN_LAYERS,maxLayers:POM_MAX_LAYERS,heightScale:POM_HEIGHT_SCALE,maxOffsetRatio:POM_MAX_OFFSET_RATIO,maxDistance:POM_MAX_DISTANCE,shadowSteps:POM_SHADOW_STEPS,shadowBias:POM_SHADOW_BIAS,shadowStrength:POM_SHADOW_STRENGTH,qualityBias:VT_QUALITY_BIAS,addressMode:1,side:THREE.DoubleSide}});bootstrap.defer(()=>pomBinding.dispose());
if(coordinator.register(pomBinding)!==FeedbackRegistrationStatus.Registered)throw new Error('Dungeon feedback capacity exceeded');
scene.add(new THREE.HemisphereLight(0xb9c8e8,0x241b15,1.6));const lamp=new THREE.PointLight(0xffc985,30,18,2);lamp.position.set(0,3.2,0);scene.add(lamp);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(16,16),new THREE.MeshStandardMaterial({color:0x292722,roughness:1}));floor.rotation.x=-Math.PI/2;scene.add(floor);const ceiling=floor.clone();ceiling.position.y=4;ceiling.rotation.x=Math.PI/2;ceiling.material=new THREE.MeshStandardMaterial({color:0x18191b,roughness:1});scene.add(ceiling);
const materialNames=['Rock064','Ground103','PavingStones150'];
const heightThree=THREE as unknown as Parameters<typeof loadHeightTextureR16>[0]; // @unsafe-cast reason=HeightThreeConstructorVariance issue=DME-030 expires=2026-10-01
const heights=await Promise.all(materialNames.map(name=>loadHeightTextureR16(heightThree,device,`dungeon-height/${name}_Height.r16`)));
const sets=materialNames.map(name=>{const paths={albedo:`${name}_Color.png`,normal:`${name}_NormalGL.png`,masks:`${name}_Masks.png`},dimensions=getVirtualTextureDimensions(session.header,paths.albedo);return store.loadMaterialSet(paths,{...dimensions,mipTail:true})});
const segments:Array<readonly[number,number,number,number]>=[[-8,-8,8,-8],[8,-8,8,8],[8,8,-8,8],[-8,8,-8,-8],[-3,-8,-3,1],[-3,1,2,1],[2,1,2,8],[3,-8,3,-1],[-2,-1,3,-1],[-2,-1,-2,5],[-2,5,4,5],[4,5,4,8]];
type Wall={x1:number;z1:number;x2:number;z2:number};const walls:Array<Wall|null>=new Array(12).fill(null);
for(let i=0;i<segments.length;i++){const segment=segments[i],set=sets[i%sets.length],height=heights[i%heights.length];if(!segment||!set||!height)throw new Error('Dungeon material layout incomplete');const[x1,z1,x2,z2]=segment,dx=x2-x1,dz=z2-z1,len=Math.hypot(dx,dz),geometry=new THREE.PlaneGeometry(len,4);geometry.setAttribute('tangent',new THREE.BufferAttribute(new Float32Array([1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1]),4));const wallUv=geometry.getAttribute('uv');for(let u=0;u<wallUv.count;u++)wallUv.setX(u,wallUv.getX(u)*len/4);const placeholder=new THREE.MeshStandardMaterial(),mesh=new THREE.Mesh(geometry,placeholder);mesh.position.set((x1+x2)/2,2,(z1+z2)/2);mesh.rotation.y=Math.atan2(-dz,dx);scene.add(mesh);pomBinding.add(mesh,set,height as unknown as THREE.Texture);placeholder.dispose();walls[i]={x1,z1,x2,z2}} // @unsafe-cast reason=HeightTextureStructuralType issue=DME-030 expires=2026-10-01
pomBinding.seal();
const PLAYER_RADIUS=.28,pose={x:-5.5,z:-5.5,yaw:0,pitch:0};let programmatic=false,pomEnabled=true,hudVisible=true,smoothedDt=1/60;
const input=new BoundedKeyboardInput();bootstrap.defer(()=>input.dispose());
const relativePointer=new RelativePointerInput(host.renderer.domElement,(x,y)=>{if(!programmatic){pose.yaw-=x*.002;pose.pitch=Math.max(-1.45,Math.min(1.45,pose.pitch-y*.002))}});bootstrap.defer(()=>relativePointer.dispose());
const errors=new BrowserErrorCapture(runtime.diagnostics);bootstrap.defer(()=>errors.dispose());const steps=new FrameStepHarness(64),hud=new TextHud(document.getElementById('hud'));
const timing={vtCpuUs:0,renderSubmitUs:0,feedbackSubmitUs:0,frameCpuUs:0,gpuMainMs:0,gpuFeedbackMs:0,gpuTotalMs:0,gpuTimestampSupported:host.timestampSupported};
/** @alloc-effect none */function pointDistance(x:number,z:number,w:Wall):number{const dx=w.x2-w.x1,dz=w.z2-w.z1,l2=dx*dx+dz*dz,t=Math.max(0,Math.min(1,((x-w.x1)*dx+(z-w.z1)*dz)/l2));return Math.hypot(x-(w.x1+t*dx),z-(w.z1+t*dz))}
/** @alloc-effect none */function valid(x:number,z:number):boolean{if(!(x>-7.7&&x<7.7&&z>-7.7&&z<7.7))return false;for(let i=4;i<walls.length;i++){const wall=walls[i];if(wall&&pointDistance(x,z,wall)<=PLAYER_RADIUS)return false}return true}
/** @alloc-effect none */function setPose(x:number,z:number,yaw=pose.yaw,pitch=pose.pitch):void{if(valid(x,z)){pose.x=x;pose.z=z}pose.yaw=yaw;pose.pitch=Math.max(-1.45,Math.min(1.45,pitch))}
/** @alloc-effect none */function move(forward:number,strafe:number):void{const sin=Math.sin(pose.yaw),cos=Math.cos(pose.yaw),dx=-sin*forward+cos*strafe,dz=-cos*forward-sin*strafe;if(valid(pose.x+dx,pose.z))pose.x+=dx;if(valid(pose.x,pose.z+dz))pose.z+=dz}
/** @alloc-effect none */function setPomEnabled(enabled:boolean):void{pomEnabled=enabled;pomBinding.setPomEnabled(enabled)}
/** @alloc-effect diagnostic */function updateHud():void{const d=store.getStats(),status=relativePointer.getStatus();hud.setText(`afterglow — Engine Dungeon\n3 × 8K PBR sets · 12 walls · ${Math.round(1/smoothedDt)} FPS\nPosition ${pose.x.toFixed(2)}, ${pose.z.toFixed(2)} · ${status.eventType}\nPOM ${pomEnabled?'8–32 layers · 8-step self-shadow':'off'}\nResident ${d.atlasSlotsUsed}/${d.atlasSlotsTotal} · pending ${d.pendingPages}\nErrors ${runtime.diagnostics.count}`)}
/** @alloc-effect none */function updateFrame(frame:Readonly<RenderFrame>):void{const frameStarted=performance.now(),dt=Math.min(.05,frame.deltaSeconds);smoothedDt=smoothedDt*.95+dt*.05;coordinator?.recordFrameTime(dt*1000);if(!programmatic){let f=(input.isDown(DemoInputAction.ZoomIn)?1:0)-(input.isDown(DemoInputAction.ZoomOut)?1:0),s=(input.isDown(DemoInputAction.OrbitRight)?1:0)-(input.isDown(DemoInputAction.OrbitLeft)?1:0),speed=input.isDown(DemoInputAction.Sprint)?5.5:2.8;if(f||s){const n=Math.hypot(f,s);move(f/n*speed*dt,s/n*speed*dt)}if(input.consumePressed(DemoInputAction.ResetView))setPose(-5.5,-5.5,0,0);if(input.consumePressed(DemoInputAction.PixelView))setPomEnabled(!pomEnabled);if(input.consumePressed(DemoInputAction.ModelOne))setPose(-5.5,-5.5,0,0);if(input.consumePressed(DemoInputAction.ModelTwo))setPose(5.5,-5.5,Math.PI,0);if(input.consumePressed(DemoInputAction.PoseThree))setPose(5.5,6.5,-Math.PI/2,0)}camera.position.set(pose.x,1.7,pose.z);camera.rotation.set(pose.pitch,pose.yaw,0);camera.updateMatrixWorld();lamp.position.set(pose.x,3.1,pose.z);steps.poll(frame.frameId);timing.vtCpuUs=coordinator?.vtCpuUs??0;timing.renderSubmitUs=host.renderSubmitUs;timing.feedbackSubmitUs=coordinator?.feedbackSubmitUs??0;timing.frameCpuUs=(performance.now()-frameStarted)*1000;if(hudVisible&&frame.frameId%15===0)updateHud()} // @alloc-allowed reason=DiagnosticHud issue=DME-034 expires=2026-10-01
if(runtime.registerWorker(coordinator)!==RegistrationStatus.Registered||runtime.registerRenderPass(host)!==RegistrationStatus.Registered||runtime.registerRenderPass(coordinator)!==RegistrationStatus.Registered)throw new Error('Dungeon runtime capacity exceeded');
runtime.enterWarmup();await validatePomShaderWarmup(host,async()=>{runtime.adapter.warmAllDescriptors();pomBinding.setPomEnabled(false);await host.warm();await activeCoordinator.warm();pomBinding.setPomEnabled(true);await host.warm();await activeCoordinator.warm();await runtime.warm()});host.renderer.render(scene,camera);host.attachVirtualTextureStore(store);for(const height of heights)host.assertHeightTextureFormat(height);runtime.sealGameplay();
const shutdown=new PageShutdown(()=>{runtime.stop();relativePointer.dispose();input.dispose();errors.dispose();pomBinding.dispose();store.dispose();void session.close();runtime.dispose()});bootstrap.defer(()=>shutdown.dispose());runtime.start({update:updateFrame});
const step=(count=1):Promise<void>=>steps.wait(runtime.frame.frameId,Math.max(1,count|0));
function atlasFeedback(groups:number,start=0):Map<number,{path:string;mip:number;x:number;y:number}>{const map=new Map(),entries=sets.map(set=>set.albedo);for(let i=0;i<groups;i++){const entry=entries[i%entries.length];if(!entry)continue;const local=start+Math.floor(i/entries.length),page=local%(entry.pageGridX*entry.pageGridY);map.set(i,{path:entry.path,mip:0,x:page%entry.pageGridX,y:Math.floor(page/entry.pageGridX)})}return map}
async function waitIdle(timeout=15000):Promise<boolean>{const end=performance.now()+timeout;while(performance.now()<end){const s=store.getStats();if(!s.pendingPages&&!s.scheduledRequests&&!s.readyUploads)return true;await step(1)}return false}
async function runAtlasScenario(name:string,timeout=120000):Promise<object>{if(!['cold','half','full','churn'].includes(name))throw new Error(`unknown atlas scenario ${name}`);programmatic=true;pomBinding.setFeedbackEnabled(false);try{const initial=store.getStats(),total=initial.atlasSlotsTotal,target=name==='half'?Math.floor(total/2):name==='cold'?initial.atlasSlotsUsed:Math.floor(total*.995),feedback=atlasFeedback(Math.ceil(Math.max(0,target-initial.atlasSlotsUsed)/3)+32,name==='half'?0:1024);if(name!=='cold')store.processFeedback(feedback);let end=performance.now()+timeout;while(performance.now()<end){const s=store.getStats();if(s.atlasSlotsUsed>=target&&!s.pendingPages&&!s.scheduledRequests&&!s.readyUploads)break;if(name!=='cold')store.processFeedback(feedback);await step(FEEDBACK_INTERVAL)}if(name==='churn'){const before=store.getStats().cacheEvictions,replacement=atlasFeedback(Math.ceil(total/3),3072);for(let epoch=0;epoch<17;epoch++)store.processFeedback(replacement);end=performance.now()+timeout;while(performance.now()<end){const s=store.getStats();if(s.cacheEvictions>before&&!s.pendingPages&&!s.scheduledRequests&&!s.readyUploads)break;store.processFeedback(replacement);await step(FEEDBACK_INTERVAL)}}return{name,target,...store.getStats(),timing:{...timing},errors:runtime.diagnostics.count}}finally{pomBinding.setFeedbackEnabled(true)}}
const scenarios:Record<string,()=>void>={forward:()=>setPose(-5.5,-5.5,0,0),reverse:()=>setPose(5.5,-5.5,Math.PI,0),corner:()=>setPose(5.8,6.4,-Math.PI/2,-.2)};
const pipelineStats={renderPipelines:0,computePipelines:0,renderPipelineViolations:0,computePipelineViolations:0};
publishDevHarness('__afterglowDungeon',{ready:()=>true,telemetry:()=>store.getStats(),timing:()=>timing,inputStatus:()=>relativePointer.getStatus(),pomStatus:()=>({enabled:pomEnabled,minLayers:POM_MIN_LAYERS,maxLayers:POM_MAX_LAYERS,heightScale:POM_HEIGHT_SCALE,maxOffsetRatio:POM_MAX_OFFSET_RATIO,maxDistance:POM_MAX_DISTANCE,selfShadowSteps:POM_SHADOW_STEPS,selfShadowStrength:POM_SHADOW_STRENGTH,heightSource:'resident ambientCG displacement',heightFormat:'r32float-from-r16'}),setPomEnabled,setFeedbackEnabled:(enabled:boolean)=>pomBinding.setFeedbackEnabled(enabled),pipelineTelemetry:()=>{const seal=host.sealMonitor;pipelineStats.renderPipelines=seal.renderPipelines;pipelineStats.computePipelines=seal.computePipelines;pipelineStats.renderPipelineViolations=seal.renderPipelineViolations;pipelineStats.computePipelineViolations=seal.computePipelineViolations;return pipelineStats},resolveGpuTimings:async()=>coordinator?.resolveGpuTimings(timing)??timing,setGpuTimingEnabled:(enabled:boolean)=>coordinator?.setGpuTimingEnabled(enabled),errorCount:()=>runtime.diagnostics.count,runAtlasScenario,snapshot:()=>({pose:{...pose},...store.getDebugSnapshot(),requests:0,feedbackMips:[],errors:errors.snapshot()}),setProgrammatic:(enabled:boolean)=>{programmatic=enabled;input.programmatic=enabled;input.clear()},setHudVisible:(visible:boolean)=>{hudVisible=visible;hud.setVisible(visible)},setPose,getPose:()=>({...pose}),move,look:(yaw:number,pitch:number)=>setPose(pose.x,pose.z,pose.yaw+yaw,pose.pitch+pitch),step,waitForIdle:waitIdle,runScenario:async(name:string)=>{const scenario=scenarios[name];if(!scenario)throw new Error(`unknown scenario ${name}`);programmatic=true;scenario();await step(120);await waitIdle();await step(16);await waitIdle();return{pose:{...pose},...store.getDebugSnapshot(),errors:errors.snapshot()}}});
bootstrap.release();console.log('afterglow-engine: canonical Dungeon started');
}catch(error){try{await bootstrap.rollback()}catch(cleanup){if(error instanceof Error&&error.cause===undefined)error.cause=cleanup}throw error}
