import {
  TelemetryDescriptorKind,
  TelemetryMetricKind,
  type TelemetryDescriptor,
  type TelemetryMetricDescriptor,
} from './telemetry.ts';

export const enum EngineTelemetryCategory {
  Runtime = 0,
  Frame = 1,
  Worker = 2,
  VirtualTexture = 3,
  Asset = 4,
  Texture = 5,
  Gpu = 6,
  Audio = 7,
  Host = 8,
  Rpc = 9,
  Model = 10,
  Storage = 11,
}

export const enum EngineTraceDescriptor {
  Frame = 0,
  WorkerPoll = 1,
  VirtualTexture = 2,
  StructuralCommands = 3,
  PoseBatches = 4,
  RenderPrepare = 5,
  GameUpdate = 6,
  RenderPasses = 7,
  AssetCompositionOpen = 8,
  AssetSize = 9,
  AssetRead = 10,
  AssetBulkRead = 11,
  RpcCall = 12,
  VtPageLoad = 13,
  VtBulkWait = 14,
  VtBulkDispatch = 15,
  TextureTranscodeQueue = 16,
  TextureTranscode = 17,
  VtUpload = 18,
  /** Reserved for decoding pre-removal AGTB captures; no runtime producer. */
  CacheRead = 19,
  /** Reserved for decoding pre-removal AGTB captures; no runtime producer. */
  CacheWrite = 20,
  MeshOptimize = 21,
  VtFeedbackDetected = 22,
  VtSchedulerWait = 23,
  VtPagePublished = 24,
  MutableTextureWrite = 25,
  MutablePageRefresh = 26,
  ModelRevision = 27,
  ModelPublished = 28,
  GeometryUpload = 29,
  BlobRead = 30,
  BlobWrite = 31,
}

export const ENGINE_TRACE_DESCRIPTORS: readonly TelemetryDescriptor[] = [
  { category: EngineTelemetryCategory.Frame, categoryName: 'frame', name: 'frame', kind: TelemetryDescriptorKind.Span, argument0: 'frame_id', argument1: 'delta_ns' },
  { category: EngineTelemetryCategory.Worker, categoryName: 'worker', name: 'worker.poll', kind: TelemetryDescriptorKind.Span, argument0: 'stage', argument1: 'elapsed_us' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt.update', kind: TelemetryDescriptorKind.Span, argument0: 'stage', argument1: 'elapsed_us' },
  { category: EngineTelemetryCategory.Runtime, categoryName: 'runtime', name: 'structural.commands', kind: TelemetryDescriptorKind.Span, argument0: 'stage', argument1: 'elapsed_us' },
  { category: EngineTelemetryCategory.Runtime, categoryName: 'runtime', name: 'pose.batches', kind: TelemetryDescriptorKind.Span, argument0: 'stage', argument1: 'elapsed_us' },
  { category: EngineTelemetryCategory.Frame, categoryName: 'frame', name: 'render.prepare', kind: TelemetryDescriptorKind.Span, argument0: 'stage', argument1: 'elapsed_us' },
  { category: EngineTelemetryCategory.Runtime, categoryName: 'runtime', name: 'game.update', kind: TelemetryDescriptorKind.Span, argument0: 'frame_id' },
  { category: EngineTelemetryCategory.Frame, categoryName: 'frame', name: 'render.passes', kind: TelemetryDescriptorKind.Span, argument0: 'frame_id' },
  { category: EngineTelemetryCategory.Asset, categoryName: 'asset', name: 'asset.composition.open', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'workers', argument1: 'status' },
  { category: EngineTelemetryCategory.Asset, categoryName: 'asset', name: 'asset.size', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'status' },
  { category: EngineTelemetryCategory.Asset, categoryName: 'asset', name: 'asset.read', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'offset_or_status' },
  { category: EngineTelemetryCategory.Asset, categoryName: 'asset', name: 'asset.read_bulk', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'spans' },
  { category: EngineTelemetryCategory.Rpc, categoryName: 'rpc', name: 'rpc.call', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'method', argument1: 'bytes' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt.page_load', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'status' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt.bulk_wait', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'tier' },
  { category: EngineTelemetryCategory.Asset, categoryName: 'asset', name: 'asset.bulk_dispatch', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'spans' },
  { category: EngineTelemetryCategory.Texture, categoryName: 'texture', name: 'texture.transcode_queue', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'format' },
  { category: EngineTelemetryCategory.Texture, categoryName: 'texture', name: 'texture.transcode', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'format' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt.upload', kind: TelemetryDescriptorKind.Span, argument0: 'bytes', argument1: 'slot' },
  // IDs 19–20 remain reserved so historical pre-removal captures decode without ABI drift.
  { category: EngineTelemetryCategory.Asset, categoryName: 'cache', name: 'cache.read', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'hit' },
  { category: EngineTelemetryCategory.Asset, categoryName: 'cache', name: 'cache.write', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'status' },
  { category: EngineTelemetryCategory.Asset, categoryName: 'asset', name: 'mesh.optimize', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'status' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt.feedback_detected', kind: TelemetryDescriptorKind.Instant, argument0: 'priority', argument1: 'feedback_epoch' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt.scheduler_wait', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'priority', argument1: 'status' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt.page_published', kind: TelemetryDescriptorKind.Instant, argument0: 'physical_slot', argument1: 'eligible_frame_id' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt.mutable_write', kind: TelemetryDescriptorKind.Instant, argument0: 'bytes', argument1: 'status' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt.mutable_refresh', kind: TelemetryDescriptorKind.Span, argument0: 'pages', argument1: 'remaining' },
  { category: EngineTelemetryCategory.Model, categoryName: 'model', name: 'model.revision', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'revision', argument1: 'status' },
  { category: EngineTelemetryCategory.Model, categoryName: 'model', name: 'model.published', kind: TelemetryDescriptorKind.Instant, argument0: 'revision', argument1: 'cpu_bytes' },
  { category: EngineTelemetryCategory.Model, categoryName: 'model', name: 'geometry.upload', kind: TelemetryDescriptorKind.Span, argument0: 'bytes', argument1: 'slot' },
  { category: EngineTelemetryCategory.Storage, categoryName: 'storage', name: 'blob.read', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'status' },
  { category: EngineTelemetryCategory.Storage, categoryName: 'storage', name: 'blob.write', kind: TelemetryDescriptorKind.AsyncSpan, argument0: 'bytes', argument1: 'status' },
];

export const FRAME_BUDGET_TRACE_DESCRIPTORS: readonly number[] = [
  EngineTraceDescriptor.WorkerPoll,
  EngineTraceDescriptor.VirtualTexture,
  EngineTraceDescriptor.StructuralCommands,
  EngineTraceDescriptor.PoseBatches,
  EngineTraceDescriptor.RenderPrepare,
];

export const enum EngineMetric {
  Frames = 0,
  FrameDeltaNs = 1,
  FrameMaxNs = 2,
  AssetBytesRead = 3,
  AssetReadNs = 4,
  RpcCalls = 5,
  RpcNs = 6,
  VtPagesRequested = 7,
  VtPagesLoaded = 8,
  VtPagesFailed = 9,
  VtUploadNs = 10,
  TextureTranscodeNs = 11,
  MutableTextureWrites = 12,
  MutableTextureBytes = 13,
  MutablePagesPublished = 14,
  MutablePagesDeferred = 15,
  ModelRevisionsQueued = 16,
  ModelRevisionsPublished = 17,
  ModelRevisionsFailed = 18,
  ModelCpuBytesHighWater = 19,
  ModelGpuBytesHighWater = 20,
  GeometryUploadNs = 21,
  BlobReadBytes = 22,
  BlobWriteBytes = 23,
}

export const ENGINE_METRIC_DESCRIPTORS: readonly TelemetryMetricDescriptor[] = [
  { category: EngineTelemetryCategory.Frame, categoryName: 'frame', name: 'frames', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.Frame, categoryName: 'frame', name: 'frame_delta_ns', kind: TelemetryMetricKind.HistogramLog2, unit: 'nanoseconds' },
  { category: EngineTelemetryCategory.Frame, categoryName: 'frame', name: 'frame_max_ns', kind: TelemetryMetricKind.Maximum, unit: 'nanoseconds' },
  { category: EngineTelemetryCategory.Asset, categoryName: 'asset', name: 'asset_bytes_read', kind: TelemetryMetricKind.Counter, unit: 'bytes' },
  { category: EngineTelemetryCategory.Asset, categoryName: 'asset', name: 'asset_read_ns', kind: TelemetryMetricKind.HistogramLog2, unit: 'nanoseconds' },
  { category: EngineTelemetryCategory.Rpc, categoryName: 'rpc', name: 'rpc_calls', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.Rpc, categoryName: 'rpc', name: 'rpc_duration_ns', kind: TelemetryMetricKind.HistogramLog2, unit: 'nanoseconds' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt_pages_requested', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt_pages_loaded', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt_pages_failed', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'vt_upload_ns', kind: TelemetryMetricKind.HistogramLog2, unit: 'nanoseconds' },
  { category: EngineTelemetryCategory.Texture, categoryName: 'texture', name: 'texture_transcode_ns', kind: TelemetryMetricKind.HistogramLog2, unit: 'nanoseconds' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'mutable_texture_writes', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'mutable_texture_bytes', kind: TelemetryMetricKind.Counter, unit: 'bytes' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'mutable_pages_published', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.VirtualTexture, categoryName: 'vt', name: 'mutable_pages_deferred', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.Model, categoryName: 'model', name: 'model_revisions_queued', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.Model, categoryName: 'model', name: 'model_revisions_published', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.Model, categoryName: 'model', name: 'model_revisions_failed', kind: TelemetryMetricKind.Counter, unit: 'count' },
  { category: EngineTelemetryCategory.Model, categoryName: 'model', name: 'model_cpu_bytes_high_water', kind: TelemetryMetricKind.Maximum, unit: 'bytes' },
  { category: EngineTelemetryCategory.Model, categoryName: 'model', name: 'model_gpu_bytes_high_water', kind: TelemetryMetricKind.Maximum, unit: 'bytes' },
  { category: EngineTelemetryCategory.Model, categoryName: 'model', name: 'geometry_upload_ns', kind: TelemetryMetricKind.HistogramLog2, unit: 'nanoseconds' },
  { category: EngineTelemetryCategory.Storage, categoryName: 'storage', name: 'blob_read_bytes', kind: TelemetryMetricKind.Counter, unit: 'bytes' },
  { category: EngineTelemetryCategory.Storage, categoryName: 'storage', name: 'blob_write_bytes', kind: TelemetryMetricKind.Counter, unit: 'bytes' },
];
