[package]
name = "agx"
version = "0.1.0"
edition = "2024"

[dependencies]
afterglow-engine = { path = "../afterglow-engine" }
bevy.workspace = true
clap.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasm-bindgen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { workspace = true, features = ["dynamic_linking", "bevy_dev_tools", "sysinfo_plugin", "trace", "trace_chrome"] }
