[package]
name = "prototype-physics-serialize"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.1", default-features = false, features = ["bevy_core_pipeline", "bevy_pbr", "x11"] }
avian3d = { version = "0.6.1", default-features = false, features = ["3d", "f32", "parry-f32", "enhanced-determinism", "serialize"] }
postcard = { version = "1", features = ["alloc"] }
serde = { version = "1", features = ["derive"] }
