#!/usr/bin/env bash
set -euo pipefail
SCENARIO="${1:-cold}"
OUTPUT="${2:-vt-atlas-${SCENARIO}-$(date +%Y%m%d-%H%M%S).log}"
TIMEOUT_MS="${VT_ATLAS_TIMEOUT_MS:-180000}"
PORT="${AFTERGLOW_DEVTOOLS_PORT:-9222}"
case "$SCENARIO" in cold|half|full|churn) ;; *) echo "scenario must be cold, half, full, or churn" >&2; exit 2;; esac
curl -sf "http://127.0.0.1:${PORT}/json/version" >/dev/null || {
  echo "no VT dungeon DevTools endpoint; run DISPLAY=:0 ./scripts/run-dungeon.sh first" >&2; exit 1;
}
[[ -x target/release/latency-tool ]] || cargo build --release -p latency-tool
EXPR="(async()=>{const a=window.__afterglowDungeon;if(!a)throw new Error('VT dungeon API unavailable');const scenario='${SCENARIO}',samples=[];let longTaskCount=0,longTaskMs=0,longTaskMaxMs=0,frames=0,over17=0,maxFrameMs=0,sumFrameMs=0,last=-1,running=true;const observer=typeof PerformanceObserver==='function'&&PerformanceObserver.supportedEntryTypes?.includes('longtask')?new PerformanceObserver(list=>{for(const entry of list.getEntries()){longTaskCount++;longTaskMs+=entry.duration;longTaskMaxMs=Math.max(longTaskMaxMs,entry.duration)}}):null;observer?.observe({entryTypes:['longtask']});function raf(now){if(last>=0){const dt=now-last;frames++;sumFrameMs+=dt;maxFrameMs=Math.max(maxFrameMs,dt);if(dt>17)over17++}last=now;if(running)requestAnimationFrame(raf)}requestAnimationFrame(raf);let sampling=false;const timer=setInterval(async()=>{if(sampling)return;sampling=true;await a.resolveGpuTimings();const s=a.telemetry(),t=a.timing(),m=performance.memory;samples.push({second:samples.length,resident:s.atlasSlotsUsed,pending:s.pendingPages,pendingBytes:s.pendingBytes,scheduled:s.scheduledRequests,readyUploads:s.readyUploads,evictions:s.cacheEvictions,rejected:s.rejectedAdmissions,vtCpuUs:t.vtCpuUs,renderSubmitUs:t.renderSubmitUs,feedbackSubmitUs:t.feedbackSubmitUs,frameCpuUs:t.frameCpuUs,gpuTimingValid:t.gpuTimingValid,resolvedFrameId:t.resolvedFrameId,gpuSceneMs:t.gpuSceneMs,gpuOutputMs:t.gpuOutputMs,gpuFeedbackMs:t.gpuFeedbackMs,gpuTotalMs:t.gpuTotalMs,usedJsHeap:m?.usedJSHeapSize??null,totalJsHeap:m?.totalJSHeapSize??null});sampling=false},1000);const heapStart=performance.memory?.usedJSHeapSize??null,start=performance.now();const result=await a.runAtlasScenario(scenario,${TIMEOUT_MS});await a.resolveGpuTimings();const durationMs=performance.now()-start;running=false;clearInterval(timer);observer?.disconnect();const heapEnd=performance.memory?.usedJSHeapSize??null;return JSON.stringify({scenario,durationMs,frames,meanFrameMs:frames?sumFrameMs/frames:0,maxFrameMs,over17,longTaskCount,longTaskMs,longTaskMaxMs,heapStart,heapEnd,heapDelta:heapStart===null||heapEnd===null?null:heapEnd-heapStart,gpuTimestampSupported:a.timing().gpuTimestampSupported,gpuTimingValid:a.timing().gpuTimingValid,resolvedFrameId:a.timing().resolvedFrameId,gpuSceneMs:a.timing().gpuSceneMs,gpuOutputMs:a.timing().gpuOutputMs,gpuFeedbackMs:a.timing().gpuFeedbackMs,gpuTotalMs:a.timing().gpuTotalMs,pipelines:a.pipelineTelemetry(),samples,result})})()"
./target/release/latency-tool eval "$EXPR" "127.0.0.1:${PORT}" | tee "$OUTPUT"
