//! afterglow-engine build orchestrator (`cargo run -p xtask <cmd>`).
//!
//! Commands:
//!   build   — build the native CEF host + examples
//!   wasm    — build the engine core to WASM (web worker)
//!   dist    — assemble the distributable (native binary + CEF + assets)
//!   check   — cargo check the whole workspace
//!   gen-ts  — run the RPC schema dump and generate TypeScript clients

use std::process::Command;

fn main() {
    let cmd = std::env::args().nth(1).unwrap_or_else(|| {
        eprintln!("usage: cargo run -p xtask <build|wasm|dist|check|gen-ts>");
        std::process::exit(2);
    });
    let r = match cmd.as_str() {
        "build" => build(),
        "wasm" => wasm(),
        "dist" => dist(),
        "check" => sh("cargo", &["check", "--workspace"]),
        "gen-ts" => gen_ts(),
        "gen-ts-runtime" => gen_ts_runtime(),
        other => { eprintln!("unknown command: {other}"); 2 }
    };
    std::process::exit(r);
}

fn build() -> i32 { sh("cargo", &["build", "--example", "minimal"]) }

fn wasm() -> i32 {
    // Build the engine core to a WASM cdylib for the web worker.
    // Requires the wasm32-unknown-unknown target + wasm-bindgen-cli.
    let r = sh("cargo", &["build", "-p", "afterglow-engine-core",
        "--target", "wasm32-unknown-unknown", "--release"]);
    if r != 0 { return r; }
    eprintln!("WASM core built -> target/wasm32-unknown-unknown/release/");
    eprintln!("next: wasm-bindgen --target web --out-dir <assets> <.wasm>");
    0
}

fn dist() -> i32 {
    let r = sh("cargo", &["build", "--release", "--example", "minimal"]);
    if r != 0 { return r; }
    eprintln!("dist: TODO copy target/release/examples/minimal + CEF runtime + assets -> dist/");
    0
}

fn sh(program: &str, args: &[&str]) -> i32 {
    let status = Command::new(program).args(args).status();
    match status {
        Ok(s) => s.code().unwrap_or(1),
        Err(e) => { eprintln!("failed to run {program}: {e}"); 1 }
    }
}

// --- RPC schema -> TypeScript client --------------------------------------

fn gen_ts() -> i32 {
    // 1. Run the schema-dump bin (any crate with a #[rpc] trait + dump bin).
    let dump = Command::new("cargo")
        .args(["run", "-p", "afterglow-rpc-demo", "--bin", "dump-schema", "-q"])
        .output();
    let Ok(out) = dump else { eprintln!("failed to run dump-schema"); return 1; };
    if !out.status.success() {
        eprintln!("dump-schema failed: {}", String::from_utf8_lossy(&out.stderr));
        return 1;
    }
    let schema: serde_json::Value = match serde_json::from_slice(&out.stdout) {
        Ok(v) => v,
        Err(e) => { eprintln!("schema JSON parse: {e}"); return 1; }
    };

    let service = schema["name"].as_str().unwrap_or("Service");
    let methods = schema["methods"].as_array().expect("methods array");
    let mut ts = String::new();
    ts.push_str("// AUTO-GENERATED by `xtask gen-ts`. Do not edit.\n");
    ts.push_str("// Client for the \"");
    ts.push_str(service);
    ts.push_str("\" worker. Talks over a Transport (call -> Promise<Uint8Array>)\n");
    ts.push_str("// with postcard as the wire codec. On native CEF, the transport is the\n");
    ts.push_str("// emulated AfterglowWorker (postMessage over CEF process messages).\n");
    ts.push_str("// On web, a real Web Worker + postMessage. Both use the same postMessage API.\n\n");
    ts.push_str("import type { Transport } from \"./transport\";\n");
    ts.push_str("import { encode, decode } from \"./postcard\";\n\n");
    ts.push_str(&format!("export class {}Client {{\n", service));
    ts.push_str("  constructor(private readonly t: Transport) {}\n");
    for m in methods {
        let mname = m["name"].as_str().unwrap();
        let id = m["id"].as_u64().unwrap();
        let params = m["params"].as_array().unwrap();
        let mut sig = Vec::new();
        let mut args = Vec::new();
        for p in params {
            let pname = p[0].as_str().unwrap();
            let pty = afterglow_rpc::rust_type_to_ts(p[1].as_str().unwrap());
            sig.push(format!("{pname}: {pty}"));
            args.push(pname.to_string());
        }
        let ret = afterglow_rpc::rust_type_to_ts(m["returns"].as_str().unwrap());
        ts.push_str(&format!(
            "  async {mname}({}): Promise<{ret}> {{\n",
            sig.join(", ")
        ));
        ts.push_str(&format!(
            "    const resp = await this.t.call(\"{service}\", {id}, encode([{}]));\n",
            args.join(", ")
        ));
        ts.push_str(&format!("    return decode<{ret}>(resp);\n"));
        ts.push_str("  }\n");
    }
    ts.push_str("}\n");

    let out_dir = "crates/afterglow-rpc-demo/types";
    let _ = std::fs::create_dir_all(out_dir);
    let path = format!("{out_dir}/{}.ts", to_snake(service));
    std::fs::write(&path, ts).expect("write ts");
    eprintln!("generated {path}");
    0
}

fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i != 0 { out.push('_'); }
        out.push(c.to_ascii_lowercase());
    }
    out
}

/// Generate the TS runtime: transport.ts + postcard.ts stubs.
fn gen_ts_runtime() -> i32 {
    let dir = "crates/afterglow-rpc-demo/types";
    let _ = std::fs::create_dir_all(dir);

    std::fs::write(format!("{dir}/transport.ts"),
"// AUTO-GENERATED by `xtask gen-ts-runtime`. Do not edit.
// Transport: call(service, method_id, args) -> Promise<Uint8Array>
// On native CEF: AfterglowWorker wraps __afterglow_rpc (V8 + CEF process messages).
// On web: real Worker + postMessage. Both expose postMessage/onmessage.

export interface Transport {
  call(service: string, method: number, args: Uint8Array): Promise<Uint8Array>;
}

export class WorkerTransport implements Transport {
  private pending: ((data: Uint8Array) => void) | null = null;

  constructor(private worker: any) {
    this.worker.onmessage = (e: { data: string }) => {
      if (this.pending) {
        const p = this.pending; this.pending = null;
        const arr = new Uint8Array(e.data.length);
        for (let i = 0; i < e.data.length; i++) arr[i] = e.data.charCodeAt(i) & 0xFF;
        p(arr);
      }
    };
  }

  async call(service: string, method: number, args: Uint8Array): Promise<Uint8Array> {
    const hdr = new Uint8Array(4);
    hdr[0] = method & 0xFF; hdr[1] = (method>>8)&0xFF; hdr[2] = (method>>16)&0xFF; hdr[3] = (method>>24)&0xFF;
    const frame = new Uint8Array(4 + args.length);
    frame.set(hdr); frame.set(args, 4);
    let s = service + '\u{0000}';
    for (let i = 0; i < frame.length; i++) s += String.fromCharCode(frame[i]);
    return new Promise((res) => {
      this.pending = res;
      this.worker.postMessage(s);
    });
  }
}

export function createWorker(service: string): any {
  if (typeof AfterglowWorker !== 'undefined') return new AfterglowWorker(service);
  return new Worker(service + '.js');
}
").expect("write transport.ts");

    std::fs::write(format!("{dir}/postcard.ts"),
"// AUTO-GENERATED by `xtask gen-ts-runtime`. Do not edit.
// Minimal postcard codec (serde-compatible). Replace with a full impl if needed.

export function encode(value: any): Uint8Array {
  // Simple JSON fallback — replace with postcard for binary compat.
  const json = JSON.stringify(value);
  const enc = new TextEncoder();
  return enc.encode(json);
}

export function decode<T>(bytes: Uint8Array): T {
  const dec = new TextDecoder();
  return JSON.parse(dec.decode(bytes));
}
").expect("write postcard.ts");

    eprintln!("generated {dir}/transport.ts + {dir}/postcard.ts");
    0
}
