//! afterglow-engine build orchestrator (`cargo run -p xtask <cmd>`).
//!
//! Commands:
//!   build   — build the native CEF host + examples
//!   wasm [--release] — build wasm services and copy artifacts into `www/`
//!   conformance — run harsh authored-web architecture/type/allocation gates
//!   check       — cargo check the workspace + conformance gates
//!   test        — run all tests + conformance gates
//!   serve — bounded COOP/COEP development asset server
//!   release-gate — tests, docs, and current GPU/soak evidence
//!   bench       — run the native ring buffer stress test

use std::path::PathBuf;
use std::process::Command;

fn main() {
    let cmd = std::env::args().nth(1).unwrap_or_else(|| {
        eprintln!(
            "usage: cargo run -p xtask <build|wasm [--release]|serve|conformance|check|test|release-gate|bench>"
        );
        std::process::exit(2);
    });
    let r = match cmd.as_str() {
        "build" => sh(
            "cargo",
            &["build", "--example", "minimal", "-p", "afterglow-cef"],
        ),
        "wasm" => wasm(std::env::args().any(|arg| arg == "--release")),
        "serve" => sh(
            "cargo",
            &["run", "-p", "afterglow-web", "--example", "coep_server"],
        ),
        "conformance" => conformance(),
        "check" => check_all(),
        "test" => test_all(),
        "release-gate" => release_gate(),
        "bench" => sh(
            "cargo",
            &[
                "run",
                "--release",
                "--example",
                "bench_rpc",
                "-p",
                "afterglow-rpc-demo",
            ],
        ),
        other => {
            eprintln!("unknown command: {other}");
            2
        }
    };
    std::process::exit(r);
}

const WASM_TARGET: &str = "wasm32-unknown-unknown";
const WASM_STD: &str = "-Zbuild-std=core,alloc,std,panic_abort";

/// Build all wasm artifacts and copy them into `crates/afterglow-web/www/`.
///
/// - `afterglow-web` cdylib  -> `www/afterglow_web.wasm` (the transport)
/// - Each worker crate (any crate with a `ts/` dir) -> `www/<trait>.wasm`
///
/// Copies are deterministic (byte-identical to the `target/` artifacts).
fn wasm(release: bool) -> i32 {
    let profile = if release { "wasm-release" } else { "wasm-dev" };
    let mut pkgs: Vec<String> = vec!["afterglow-web".into(), "afterglow-rpc-demo".into()];
    let crates_dir = workspace_root().join("crates");
    if let Ok(entries) = std::fs::read_dir(&crates_dir) {
        for entry in entries.flatten() {
            let dir = entry.path();
            if dir.join("ts").is_dir() {
                let name = entry.file_name().to_string_lossy().to_string();
                if !pkgs.contains(&name) {
                    pkgs.push(name);
                }
            }
        }
    }
    for pkg in &pkgs {
        let r = sh(
            "cargo",
            &[
                "build",
                "-p",
                pkg.as_str(),
                "--target",
                WASM_TARGET,
                WASM_STD,
                "--profile",
                profile,
            ],
        );
        if r != 0 {
            eprintln!("wasm build failed for {pkg}");
            return r;
        }
    }

    let target_dir = target_dir();
    let src = target_dir.join(WASM_TARGET).join(profile);
    let www = workspace_root().join("crates/afterglow-web/www");

    // Copy the transport wasm (afterglow-web) + JS glue.
    let copies: &[(&str, &str)] = &[("afterglow_web.wasm", "afterglow_web.wasm")];
    for (from, to) in copies {
        let from_path = src.join(from);
        let to_path = www.join(to);
        if let Err(e) = std::fs::copy(&from_path, &to_path) {
            eprintln!(
                "failed to copy {} -> {}: {e}",
                from_path.display(),
                to_path.display()
            );
            return 1;
        }
        eprintln!("copied {} -> {}", from_path.display(), to_path.display());
    }

    // Auto-detect and copy worker wasm artifacts: any crate with a `ts/`
    // directory (the #[rpc] macro writes there) is a worker crate. Its wasm
    // artifact is named after the crate name (hyphens → underscores), and
    // the TS client expects it as `<trait_name_lowercased>.wasm`.
    let crates_dir = workspace_root().join("crates");
    if let Ok(entries) = std::fs::read_dir(&crates_dir) {
        for entry in entries.flatten() {
            let crate_dir = entry.path();
            // Skip afterglow-web itself (it's the transport, not a worker).
            if crate_dir.file_name() == Some(std::ffi::OsStr::new("afterglow-web")) {
                continue;
            }
            // A worker crate has a ts/ dir (generated by #[rpc]).
            if crate_dir.join("ts").is_dir() {
                // Crate name → wasm artifact name: afterglow-assets-worker
                // → afterglow_assets_worker.wasm.
                let crate_name = entry.file_name().to_string_lossy().replace('-', "_");
                let wasm_name = format!("{crate_name}.wasm");
                let from_path = src.join(&wasm_name);
                if from_path.exists() {
                    // Find the trait name from the .client.ts file (e.g.
                    // assetloader.client.ts → trait is AssetLoader → wasm is
                    // assetloader.wasm).
                    let ts_dir = crate_dir.join("ts");
                    if let Ok(ts_entries) = std::fs::read_dir(&ts_dir) {
                        for ts in ts_entries.flatten() {
                            let name = ts.file_name().to_string_lossy().to_string();
                            if name.ends_with(".client.ts") {
                                // assetloader.client.ts → assetloader.wasm
                                let trait_lower = name.trim_end_matches(".client.ts");
                                let to_wasm = format!("{trait_lower}.wasm");
                                let to_path = www.join(&to_wasm);
                                if let Err(e) = std::fs::copy(&from_path, &to_path) {
                                    eprintln!(
                                        "failed to copy {} -> {}: {e}",
                                        from_path.display(),
                                        to_path.display()
                                    );
                                    return 1;
                                }
                                eprintln!(
                                    "copied {} -> {}",
                                    from_path.display(),
                                    to_path.display()
                                );
                            }
                        }
                    }
                }
            }
        }
    }

    // Copy generated TS clients (#[rpc] writes to <crate>/ts/*.client.ts).
    // scripts/build-web.ts emits every browser .js artifact from TypeScript.
    let crates = workspace_root().join("crates");
    if let Ok(entries) = std::fs::read_dir(&crates) {
        for entry in entries.flatten() {
            let ts_dir = entry.path().join("ts");
            if let Ok(ts_entries) = std::fs::read_dir(&ts_dir) {
                for ts in ts_entries.flatten() {
                    let path = ts.path();
                    if path.extension().is_some_and(|e| e == "ts") {
                        // Copy the .ts (for editors/IDEs).
                        let name = path.file_name().unwrap();
                        let to = www.join(name);
                        if let Err(e) = std::fs::copy(&path, &to) {
                            eprintln!("failed to copy {} -> {}: {e}", path.display(), to.display());
                            return 1;
                        }
                        eprintln!("copied {} -> {}", path.display(), to.display());
                        // All browser JavaScript is generated together below
                        // from the canonical TypeScript source graph.
                    }
                }
            }
        }
    }

    let web = Command::new("bun")
        .args(["scripts/build-web.ts"])
        .current_dir(workspace_root())
        .status();
    if !matches!(web, Ok(status) if status.success()) {
        eprintln!("failed to generate browser JavaScript from TypeScript");
        return 1;
    }

    eprintln!("wasm artifacts updated in {}", www.display());
    0
}

fn conformance() -> i32 {
    for args in [
        &["scripts/check-web-contracts.ts"][..],
        &["scripts/lint-demo-architecture.ts"][..],
        &["scripts/lint-import-boundaries.ts"][..],
        &["scripts/typecheck-ratchet.ts"][..],
        &["scripts/lint-source-hygiene.ts"][..],
        &["scripts/lint-hot-allocations.ts"][..],
        &["scripts/build-web.ts", "--check"][..],
    ] {
        let status = Command::new("bun")
            .args(args)
            .current_dir(workspace_root())
            .status();
        if !matches!(status, Ok(value) if value.success()) {
            return 1;
        }
    }
    0
}

fn check_all() -> i32 {
    let rust = sh("cargo", &["check", "--workspace"]);
    if rust != 0 {
        return rust;
    }
    conformance()
}

fn test_all() -> i32 {
    let rust = sh("cargo", &["test", "--workspace"]);
    if rust != 0 {
        return rust;
    }
    let rpc = sh(
        "node",
        &["--test", "crates/afterglow-web/tests/rpc.test.mjs"],
    );
    if rpc != 0 {
        return rpc;
    }
    if conformance() != 0 {
        return 1;
    }
    let contract_tools = Command::new("bun")
        .args([
            "test",
            "scripts/contracts.test.ts",
            "scripts/release-evidence.test.ts",
        ])
        .current_dir(workspace_root())
        .status();
    if !matches!(contract_tools, Ok(value) if value.success()) {
        return 1;
    }
    let web = Command::new("bun")
        .args([
            "test",
            "crates/afterglow-web/www/engine",
            "crates/afterglow-web/www/async-worker.test.ts",
            "crates/afterglow-web/www/physics-client.test.ts",
        ])
        .current_dir(workspace_root())
        .status();
    if matches!(web, Ok(value) if value.success()) {
        0
    } else {
        1
    }
}

fn release_gate() -> i32 {
    if test_all() != 0 {
        return 1;
    }
    let evidence = Command::new("bun")
        .arg("scripts/check-release-evidence.ts")
        .current_dir(workspace_root())
        .status();
    if !matches!(evidence, Ok(value) if value.success()) {
        return 1;
    }
    sh_in("mdbook", &["build"], &workspace_root().join("book"))
}

fn workspace_root() -> PathBuf {
    // xtask is a workspace member; CARGO_MANIFEST_DIR is the xtask crate dir.
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..")
}

fn target_dir() -> PathBuf {
    if let Ok(t) = std::env::var("CARGO_TARGET_DIR") {
        return PathBuf::from(t);
    }
    // Default: workspace-root/target.
    workspace_root().join("target")
}

fn sh(program: &str, args: &[&str]) -> i32 {
    sh_in(program, args, &workspace_root())
}

fn sh_in(program: &str, args: &[&str], directory: &std::path::Path) -> i32 {
    let status = Command::new(program)
        .args(args)
        .current_dir(directory)
        .status();
    match status {
        Ok(s) => s.code().unwrap_or(1),
        Err(e) => {
            eprintln!("failed to run {program}: {e}");
            1
        }
    }
}
