[package]
name = "afterglow-obvhs-tracer"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
glam = "0.33"
obvhs = { version = "0.3.2", default-features = false }

[workspace]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
